language: java
jdk:
- oraclejdk8
before_install: cd ff4j-console
before_deploy: pwd && ls /home/travis/build/gadogttas/ff4j-extra/ff4j-console/target
deploy:
  provider: releases
  api_key:
    secure: pdQbRCx8hRXTFPJPWfWNkieDaFjgR3deYE9QWIW5oFnnED3u6+2qNpdMrT5Xhcd+LM6OmgfukCBYBmCvHp1yKZh4O0KpBw0X8bbqvc39Yf2FcnDPHIhhw0lrx40zG9l5sUBQXPrv8jpqahOhFOgYozm64uMFFeAjSzQ7Mk8KPSnGPz29kie//Lx9B44weYVNWHIo8ZG1vUtGkhQ4GtT9Lfc8EFvLp65JZJXWjEQgTh158C2OBTKWJ0sSlQ53+gNL5prMs+lHI2byokJaEGGOdiX0o6sOAtaLaT7VwJbgSO3ZxjqHn/TBXnmvC7jDz3JtshH35N1GXprko5bXENZSiiy7XQxdDRD68KnnIIpVeoBzx4DPMWeOkwqpovPgnalke/zF1YSBvpReLwFSOHPI7MVHfJS6xPeioKIFGm/XetFt8+Qfo+EZkl19bcw3jfpaGiX6nlrTWcG993sTuqAGG1YHg/INtFh7qwctraDbvPa+tXwOEpOTYsroNvkstvzztt/sOoCj5TiP+ztD2KEAPAUJcxmY4QcIFTlJbe8mTALic3HcIj5RGdtM+HrmPbJn2/mui1ddgkHNjqzd3cebRgfzdIDbxiMlaITvxoOoglwY+RFkpRsSqNBNHB/m49Dg9hSlErB6rze5ZfF8J5rpAKbhS9A8O4y/Uyvk3GYkNio=
  file: "./target/ff4j-console.war"
  on:
    repo: gadogttas/ff4j-extra
